### ISSUE TITLE
Port this extension to Firefox?

### ISSUE THREAD

**Issue by edgardorios** [webkhung/jira_agile_instant#5]
Hello, I hope you are doing well,

Do you have plans to port this extension to Firefox any time soon?

Thanks.
Edgardo

**Comment by edgardorios** [comment]
Hello again,

FYI, I am going to fork this repository and will try to port this extension to Firefox.

Thanks.
Edgardo

**Comment by SxMShaDoW** [comment]
Hi Edardgo,

I think that is acceptable. I worked on this a long time ago and I know @webkhung probably stopped investing his time into the open source version of this.

**Comment by edgardorios** [comment]
> Hi Edardgo,

Hi @SxMShaDoW 

> I think that is acceptable. I worked on this a long time ago and I know @webkhung probably stopped investing his time into the open source version of this.

Thanks for your reply, I will do my best to make this work in Firefox, is the browser I use and would be nice to have the extension there.

If I am successful with the porting, I will let you and @webkhung know.

Thanks again!

**Comment by webkhung** [comment]
@EdgardoRios sounds good to me!

**Comment by edgardorios** [comment]
@webkhung Thank you!
